---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    appname: busybox
spec:
  containers:
    - name: busybox
      #image: quay.io/vcppds7878/busybox:latest
      image: registry.redhat.io/rhscl/postgresql-12-rhel7
      imagePullPolicy: IfNotPresent
      #command: ['sh', '-c', 'while true; do echo $(date) | tee -a /mnt/test/outfile; sync; sleep 1; done']
      env:
        - name: POSTGRESQL_DATABASE
          value: postgresdb
        - name: POSTGRESQL_USER
          value: admin
        - name: POSTGRESQL_PASSWORD
          value: psltest

      volumeMounts:
        - name: mypvc
          mountPath: /mnt/test
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: busybox-pvc
        readOnly: false
  #securityContext:
   # privileged: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 3124
    seccompProfile:
      type: RuntimeDefault
